Repository Coding-landing/YOU_ME, pull requests merged in 2023-09, with the labels that each got.

#2 [FEAT] 프로젝트 구조 생성
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/sparta/youandme/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/youandme/extension/ContextExtension.kt
  app/src/main/java/com/sparta/youandme/model/CallingObject.kt
  app/src/main/java/com/sparta/youandme/model/MainTabs.kt
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/java/com/sparta/youandme/view/call/CallFragment.kt
  app/src/main/java/com/sparta/youandme/view/detail/ContactDetailFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
  app/src/main/java/com/sparta/youandme/view/main/viewpager/MainViewPagerAdapter.kt
  app/src/main/java/com/sparta/youandme/view/mypage/MyPageFragment.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/bg_hyerin.jpg
  app/src/main/res/drawable/bg_junsun.jpg
  app/src/main/res/drawable/bg_minjong.jpg
  app/src/main/res/drawable/bg_seungchul.png
  app/src/main/res/drawable/bg_sunho.jpg
  app/src/main/res/drawable/bg_talent_1.jpg
  app/src/main/res/drawable/bg_talent_2.jpg
  app/src/main/res/drawable/bg_talent_3.jpg
  app/src/main/res/drawable/bg_talent_4.jpg
  app/src/main/res/drawable/bg_talent_5.jpg
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_call.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/sparta/youandme/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: feature

#9 [DOCS] icons & font
  README.md
  app/src/main/res/drawable/icon_add.png
  app/src/main/res/drawable/icon_back.png
  app/src/main/res/drawable/icon_color_call.png
  app/src/main/res/drawable/icon_eight.png
  app/src/main/res/drawable/icon_five.png
  app/src/main/res/drawable/icon_four.png
  app/src/main/res/drawable/icon_heart.png
  app/src/main/res/drawable/icon_letter.png
  app/src/main/res/drawable/icon_menu.png
  app/src/main/res/drawable/icon_nine.png
  app/src/main/res/drawable/icon_one.png
  app/src/main/res/drawable/icon_seven.png
  app/src/main/res/drawable/icon_six.png
  app/src/main/res/drawable/icon_tel.png
  app/src/main/res/drawable/icon_three.png
  app/src/main/res/drawable/icon_two.png
  app/src/main/res/drawable/icon_user.png
  app/src/main/res/drawable/icon_zero.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font/main_font.ttf
Labels: documentation

#11 [DESIGN] ContactListFragment 레이아웃 구성
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
  app/src/main/res/drawable/check_detail_heart.xml
  app/src/main/res/drawable/circular_background.xml
  app/src/main/res/drawable/icon_book.xml
  app/src/main/res/drawable/icon_call.xml
  app/src/main/res/drawable/icon_heart.png
  app/src/main/res/drawable/icon_heart_on.png
  app/src/main/res/drawable/icon_home.xml
  app/src/main/res/drawable/icon_list.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/item_call_info.xml
  app/src/main/res/layout/item_call_info_grid.xml
  app/src/main/res/layout/item_call_info_reversed.xml
  app/src/main/res/layout/tab_icon.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: design, feature

#14 [Design] mypagefragment
  app/src/main/res/drawable/call_11.png
  app/src/main/res/drawable/icon_blog.png
  app/src/main/res/drawable/icon_mail.png
  app/src/main/res/drawable/icon_mes1.png
  app/src/main/res/drawable/icon_sns.png
  app/src/main/res/drawable/teduri.xml
  app/src/main/res/font/main_font.ttf
  app/src/main/res/layout/fragment_my_page.xml
Labels: design, merge

#18 [FEAT] ContactListFragment 기능구현
  app/build.gradle
  app/src/main/java/com/sparta/youandme/data/CallObjectData.kt
  app/src/main/java/com/sparta/youandme/model/CallingObject.kt
  app/src/main/java/com/sparta/youandme/model/ViewType.kt
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
  app/src/main/java/com/sparta/youandme/view/main/recyclerview/adapter/ContactListAdapter.kt
  app/src/main/java/com/sparta/youandme/view/main/recyclerview/listener/ItemClickListener.kt
  app/src/main/java/com/sparta/youandme/view/main/recyclerview/utility/SwipeToEditCallback.kt
  app/src/main/java/com/sparta/youandme/view/main/viewpager/MainViewPagerAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/item_call_info.xml
  app/src/main/res/layout/item_call_info_grid.xml
  app/src/main/res/layout/item_call_info_reversed.xml
Labels: feature

#22 [FEAT] 전화 권환, 전화 걸기
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/youandme/view/call/CallFragment.kt
Labels: feature

#27 [FEAT] AddContactDialogFragment 유효성 검사 기능 추가
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/values/themes.xml
Labels: feature

#29 [DESIGN] [FIX] contact list fragment font 및 버그 수정
  app/src/main/java/com/sparta/youandme/data/CallObjectData.kt
  app/src/main/java/com/sparta/youandme/model/ViewType.kt
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
  app/src/main/java/com/sparta/youandme/view/main/recyclerview/adapter/ContactListAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/item_call_info.xml
  app/src/main/res/layout/item_call_info_grid.xml
  app/src/main/res/layout/item_call_info_reversed.xml
  app/src/main/res/values/themes.xml
Labels: bug, design

#31 [DESIGN] [FIX] mypagefragment
  app/src/main/java/com/sparta/youandme/view/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: bug, feature

#33 [DESIGN]contactdetailfragment
  app/src/main/res/drawable/icon_call2.PNG
  app/src/main/res/drawable/icon_mail2.PNG
  app/src/main/res/drawable/rounded_corner_background.xml
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: design

#34 [FEAT] 전화 관련 불편한 사항 개선 , 하이픈
  app/build.gradle
  app/src/main/java/com/sparta/youandme/view/call/CallFragment.kt
  app/src/main/java/com/sparta/youandme/view/call/CallHyphen.kt
  app/src/main/res/layout/fragment_call.xml
Labels: feature

#35 [Feature] datadelivery
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/res/drawable/dialog_back_mint.xml
  app/src/main/res/drawable/dialog_btn.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/values/colors.xml
Labels: documentation, design, feature

#36 [FEAT] mypagefragment
  app/src/main/java/com/sparta/youandme/view/mypage/MyPageFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#37 [FEAT] ContactList - AddContactDialog 데이터 송수신
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
Labels: bug, feature

#42 [FIX] 키값 중복으로 인한 이상 현상 수정
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
Labels: bug

#43 [FIX] 오류 개선
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: bug

#44 [Feat]사진 넣기 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/res/drawable/icon_user_profile.png
  app/src/main/res/layout/fragment_add_contact_dialog.xml
Labels: bug, documentation, design, feature

#45 [FEAT] 알람기능 & data class 타입 조정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/youandme/data/CallObjectData.kt
  app/src/main/java/com/sparta/youandme/model/CallingObject.kt
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/notification/AlarmReceiver.kt
  app/src/main/java/com/sparta/youandme/view/main/recyclerview/adapter/ContactListAdapter.kt
  app/src/main/res/drawable/dialog_back_green.xml
  app/src/main/res/drawable/dialog_back_green_reversed.xml
  app/src/main/res/drawable/notification_icon.xml
  app/src/main/res/layout/item_call_info.xml
  app/src/main/res/layout/item_call_info_reversed.xml
  app/src/main/res/values/themes.xml
Labels: feature

#47 Feature/contactdetailfragment
  app/src/main/java/com/sparta/youandme/view/detail/ContactDetailFragment.kt
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: design, feature

#48 [FIX] Bug 수정
  app/src/main/java/com/sparta/youandme/data/CallObjectData.kt
  app/src/main/java/com/sparta/youandme/view/main/ContactListFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
  app/src/main/res/drawable/icon_logo.png
Labels: bug

#49 [FEAT] 스플래쉬 화면 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/MainActivity.kt
  app/src/main/java/com/sparta/youandme/view/splash/SplashActivity.kt
  app/src/main/res/drawable-v24/icon_cancle.png
  app/src/main/res/drawable/sample.xml
  app/src/main/res/drawable/splash.gif
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/values/themes.xml
Labels: feature

#51 [FIX] 추가 버그 수정 및 README 추가
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sparta/youandme/data/CallObjectData.kt
  app/src/main/java/com/sparta/youandme/view/addcontact/AddContactDialogFragment.kt
  app/src/main/java/com/sparta/youandme/view/detail/ContactDetailFragment.kt
  app/src/main/java/com/sparta/youandme/view/main/recyclerview/adapter/ContactListAdapter.kt
  app/src/main/java/com/sparta/youandme/view/splash/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_add_contact_dialog.xml
  app/src/main/res/layout/fragment_my_page.xml
  icon_logo.png
  image-2.png
  image.png
Labels: bug, documentation
